//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _91011rabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int idпользователь { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Пол { get; set; }
        public string Логин { get; set; }
        public Nullable<int> Пароль { get; set; }
        public Nullable<int> Роль { get; set; }
    
        public virtual Пол Пол1 { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
