//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _91011rabota
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученики
    {
        public int idученик { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Класс { get; set; }
        public Nullable<int> Форма { get; set; }
        public Nullable<int> ОценкаРусский { get; set; }
        public Nullable<int> ОценкаМатематика { get; set; }
        public Nullable<int> ОценкаФизика { get; set; }
    
        public virtual Классы Классы { get; set; }
        public virtual Форма Форма1 { get; set; }
    }
}
